spring.application.name=StockSync

# PostgreSQL
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${SHOW_SQL}

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Encrypted key
app.security.encryption-key=${ENCRYPTION_KEY}

#
app.mercadolivre.redirect-uri=https://vividness-gratuity-foothold.ngrok-free.dev/mercadolivre/callback
